stages:
  - build
  - test
  - deploy

test:
  stage: test
  retry: 1

  image:
    name: lucasmiranda42/deepof:latest
    entrypoint: [""]

  before_script:
    - export PATH="~/.local/pipx/venvs/poetry/bin:$PATH"

  script:
    - coverage run --source deepof -m pytest
    - coverage report -m --include deepof/post_hoc.py,deepof/data.py,deepof/utils.py,deepof/model_utils.py,deepof/annotation_utils.py,deepof/models.py,deepof/hypermodels.py
    - coverage xml -o deepof_cov.xml

  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: deepof_cov.xml

deploy:

  stage: deploy
  retry: 1

  image:
    name: python:3.9.14

  script:
    - pip install deepof
