stages:
  - code_quality
  - test

code_quality:
  stage: test
  image: docker:stable
  allow_failure: true
  services:
    - docker:stable
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2378
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:12-3-stable" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    expire_in: 1 week
  dependencies: []
  only:
    refs:
      - branches
      - tags
  except:
    variables:
      - $CODE_QUALITY_DISABLED

#test:
#  stage: test
#  image: continuumio/anaconda3
#  script:
#    - pip install coverage
#    - pip install -r ./deepof/requirements.txt
#    - pip install -e deepof/
#    - coverage run -m pytest
#    - coverage report -m
#    - coverage xml -o deepof_cov.xml
#  artifacts:
#    reports:
#      cobertura: deepof_cov.xml