stages:
  - test

image: continuumio/anaconda3

test:
  stage: test
  script:
    - echo "Installing dependencies"
    - pip install -r ./deepof/requirements.txt
    - pip install -e deepof/
    - echo "Dependencies installed"
    - echo "Testing all functions in deepof.utils"
    - python -m pytest
    - echo "Testing deepof.utils complete!"