stages:
  - test

test:
  stage: test
  image: lucasmiranda42/deepof
  script:
    - pipenv run coverage run --source deepof -m pytest
    - pipenv run coverage report -m --include deepof/utils.py,deepof/preprocess.py,deepof/model_utils.py,deepof/pose_utils.py,deepof/visuals.py,deepof/models.py,deepof/hypermodels.py,deepof/train_utils.py
    - pipenv run coverage xml -o deepof_cov.xml
  artifacts:
    reports:
      cobertura: deepof_cov.xml