stages:
  - test

image: continuumio/anaconda

test_a:
  stage: test
  script:
    - echo "Testing all functions in deepof.utils"
    - pytest ./test_deepof/test_utils.py
    - echo "Testing deepof.utils complete!"