stages:
  - test

image: continuumio/anaconda

test_a:
  stage: test
  script:
    - echo "Installing dependencies"
    - pip install -r ./source/requirements.txt
    - echo "Dependencies installed"
    - echo "Testing all functions in deepof.utils"
    - pytest ./test_deepof/test_utils.py
    - echo "Testing deepof.utils complete!"