stages:
  - build
  - test

image: continuumio/anaconda3

buila:
  stage: build
  script:
    - echo "Installing dependencies"
    - pip install -r ./deepof/requirements.txt
    - pip install -e deepof/
    - echo "Dependencies installed"

test_utils:
  stage: test
  script:
    - echo "Testing all functions in deepof.utils"
    - pytest
    - echo "Testing deepof.utils complete!"