stages:
  - test
  - deploy

test:
  stage: test
  retry: 1

  image:
    name: lucasmiranda42/deepof
    entrypoint: ["pipenv", "run"]

  script:
    - pip uninstall deepof
    - coverage run --source deepof -m pytest
    - coverage report -m --include deepof/post_hoc.py,deepof/data.py,deepof/utils.py,deepof/unsupervised_utils.py,deepof/supervised_utils.py,deepof/visuals.py,deepof/models.py,deepof/hypermodels.py
    - coverage xml -o deepof_cov.xml

  artifacts:
    reports:
      cobertura: deepof_cov.xml

deploy:

  stage: deploy
  retry: 1

  image:
    name: continuumio/anaconda3:2021.05

  script:
    - pip install deepof
