[tool.poetry]
name = "deepof"
version = "0.1.85"
description = ""
authors = ["lucas_miranda <lucas_miranda@psych.mpg.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
scikit-learn = "^1.1.2"
ruptures = "^1.1.7"
tqdm = "^4.64.1"
pandas = "^1.5.0"
keras-tuner = "^1.1.3"
POT = "^0.8.2"
Shapely = "^1.8.4"
regex = "^2022.9.13"
opencv-python = "^4.6.0.66"
llvmlite = "^0.39.1"
shap = "^0.41.0"
networkx = "^2.8.7"
dask-image = "^2022.9.0"
seaborn = "^0.12.0"
seglearn = "^1.2.5"
tensorflow-macos = {version = "2.9.0", platform = "darwin"}
tensorflow = [
    {version = "2.9.0", platform = "linux"},
    {version = "2.9.0", platform = "win64"},
]
keras-tcn-macos = {version = "^1.0", platform = "darwin"}
keras-tcn = [
    {version = "^3.5.0", platform = "linux"},
    {version = "^3.5.0", platform = "win64"},
]
tensorflow-probability = "0.17.0"
tifffile = "^2022.8.12"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
pytest = "^7.1.3"
hypothesis = "^6.56.1"
sphynx = "^0.0.3"
sphinx-press-theme = "^0.8.0"
coverage = "^6.5.0"

[build-system]
requires = ["poetry==1.2.1"]
build-backend = "poetry.core.masonry.api"

